### ISSUE TITLE
RE: Hello Again Sir/Seth

### ISSUE THREAD

**Issue by silver2row** [MomsFriendlyRobotCompany/pysabertooth#2]
Exception serial.serialutil.SerialException: SerialException('Attempting to use a port that is not open',) in 
    <bound method Sabertooth.__del__ of <pysabertooth.PySabertooth.Sabertooth object at 
    0xb6b478d0>> ignored

Hello,

The above section is my issue: I am using an am335x from TI on my BeagleBone Green Wireless to interface w/ the Atmel AVR on the Sabertooth 2 x 12 w/out USB. I have leads connected to some headers on my microcontroller board (BBGW).

...

Here is the updated software:

    from pysabertooth import Sabertooth
    import time

    saber = Sabertooth("/dev/ttyO1", baudrate=9600, address=128, timeout=0.1)

    saber.drive(1, 85)
    saber.drive(2, 85)
    time.sleep(15)

    saber.stop()

    saber.drive(1, -60)
    saber.drive(2, -60)
    time.sleep(15)

    saber.stop()
    saber.close()

...

Although this software runs the motors forward and backward, stops in b/t the two directions, and then cuts off and ends the software program, I am still receiving this error. 

I have the Sabertooth switches on 1 & 2 for packetized serial.

...

Seth

P.S. Should I worry about this software "malfunction?" I do not necessarily think that it is an issue, now that I understand your library, but I would like to understand more about where the error is derived.

**Comment by silver2row** [comment]
Hello Sir,

Seth here. I have one more "issue." When running this software:

    from pysabertooth import Sabertooth
    import time

    saber = Sabertooth("/dev/ttyO1", baudrate=9600, timeout=0.1)

    #drive(number, speed)
    #number: 1-2
    #speed: -100 - 100

    def driven():

        for i in range(1):

            saber.drive(1, 85)
            saber.drive(2, 85)
            time.sleep(15)

            saber.drive(1, -60)
            saber.drive(2, -60)
            time.sleep(5)
 
            saber.stop(1)
            saber.close(2)

    driven()

...

I get this error and one of my motors keeps rotating but in the opposite direction in which the software made it turn:

    Traceback (most recent call last):
      File "Saber.py", line 25, in <module>
        driven()
      File "Saber.py", line 22, in driven
        saber.stop(1)
    TypeError: stop() takes exactly 1 argument (2 given)

Seth

P.S. I know this is annoying of me. Please, if you can find time, reply to let me know exactly how I am going about this incorrectly. Thank you for any advice.

**Comment by silver2row** [comment]
Hello Sir,

I think the saber.close() function was giving me trouble. 

Seth
